### ISSUE TITLE
[Feature request] Integration with mangareader.net

### ISSUE THREAD

**Issue by shader301202** [myh1000/mal-autosync-manga#2]
Hello. Would it be possible to make this extension compatible with http://www.mangareader.net/ ? Because I use the [MangaViewer](https://chrome.google.com/webstore/detail/manga-viewer/bebalkdfejapnfbngpmhchkboajaofen) extension for reading manga and I am most of the time using mangareader (cause the websites that your extension supports are I think only available in the Patreon version). Today I've found out that your extension exists. I'd like to autosync my manga status with mal when I'm reading on mangareader.net. Could you please add it?

**Comment by myh1000** [comment]
Sure, I just added support for mangareader in the most recent version: 1.1.1. 👍
